name: Distribution Builds

on:
  push:
    tags:
      - v*
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - name: Cache JDK
        id: cache-jdk
        uses: actions/cache@v3
        with:
          path: jdk
          key: ${{ runner.os }}-jdk
      - name: Download JDK
        if: steps.cache-jdk.outputs.cache-hit != 'true'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon unzipJdk
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon packageDistributionForCurrentOS
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/**/**/**
