name: Distribution Builds

on:
  push:
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          - os: ubuntu-latest
            jbr: 'https://cache-redirector.jetbrains.com/intellij-jbr/jbr-17.0.6-linux-x64-b829.5.tar.gz'
          - os: windows-latest
            jbr: 'https://cache-redirector.jetbrains.com/intellij-jbr/jbr-17.0.6-windows-x64-b829.5.tar.gz'
    steps:
      - uses: actions/checkout@v3
      - name: Download jbr
        uses: carlosperate/download-file-action@v2
        id: download-file
        with:
          file-url: ${{ matrix.jbr }}
          file-name: 'java_package.tar.gz'
          location: './jre'
      - uses: actions/setup-java@v3
        with:
          distribution: 'jdkfile'
          jdkFile: jre/java_package.tar.gz
          java-version: '17.0.6'
          architecture: x64
          cache: 'gradle'
      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: --no-daemon packageDistributionForCurrentOS
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/compose/jars/${{ matrix.jar }}
